### ISSUE TITLE
Design Review (due 9/26, 8am)

### ISSUE THREAD

**Issue by saltzmanj** [saltzmanj/keyboardguys#12]
### Assignment
"This assignment is for your submission of powerpoints for weekly presentations as discussed in class last Wednesday.

You should have 3 slides, the fist of which has your project name and group members.

Slide 2 should explain your work since your initial presentations. Slide 3 should explain your plans for the coming week. You presenation should run ~ 3 minutes and we will have Q&A after each presentation.

I will randomly choose ~ 1/2 of them for Monday, the remainder for Wednesday. Also, you should be starting your Multisim schematics by now and we need to look at them for this week's meetings."

-Prof. Powell

**Comment by saltzmanj** [comment]
Any problems with the following?
[20160925_endofmonth_september_presentation.pptx](https://github.com/saltzmanj/keyboardguys/files/491834/20160925_endofmonth_september_presentation.pptx)

**Comment by saltzmanj** [comment]
Submitted, as nobody seemed to have any issue.

**Comment by MrBitSage** [comment]
Notes from presentation:
- How did we do feature extraction?
 - Did we use any rotation? No
 - Did we use any variance? No
- Might want to use a hyperbolic tangent activation function since the data we are processing is promarily binary
- Strongly advised to look into available libraries
