### ISSUE TITLE
Mid-Term Formal Design Review (Due 10/9)

### ISSUE THREAD

**Issue by saltzmanj** [saltzmanj/keyboardguys#14]
# Midterm Design Reviews
- Will take place October 10, 12, and 19
- In Thornton E316

**Things to Bring**
- Assignment submission: "packet" of information
   - submitted on Collab assignments
-"Packet"
   - 1 page synopsis of the project
       - Team member names + responsibilities
       - Description of approach
       - How project complements other ECE classes
   - 3-4 page executive summary of work done so far
       - include estimate of timelines
       - Broken down by team member
   - Block diagram of the overall project
   - Multisim Files of all schematics: undetermined part values should be labeled TBD
   - All Component data sheets
   - Current .gan file (Gantt Chart)

- Presentation Points
   - 10 minutes of presentation
      - approximately 10 slides
   - Involve all team members
   - 1 slide should include a summary of your synopsis
   - Include block diagram
   - Include "interesting" parts of the schematic
   - Can include appendix slides for answering questions with
   - Include results of any preliminary testing that's been performed
   - Explain if your testing has caused design modifications
   - Explain each team member's primary responsibilities. Show how tasks are being parallelized
   - Whoever is responsible for each task should be presenting on it
   - Include flow chart for microcontroller algorithms
      - Think about UI
      - Explain whether chosen platform would be desirable if project were to go into mass production
   - Explain how project will be tested
      - Consider points for DFT (Design for test)
      - Make the reviewers aware of how testability is part of the design
      - Present a clear, logical testing plan in the form of a decision tree
      - Give an analysis of the likely failure modes
   - Explain the current status of the project
   - Include the original Gantt chart and compare
   - Expect about 2 minutes for tough questions
      - Know your circuit and software well
      - It is "somewhat" okay not to know the answer to every question
         - You can speculate: but say so and offer evidence
   - Need **clear evidence of progress**

- Copy of Multisim and .gan files will be part of the assignment

**Mechanics**
- October 10th: Seeking 6 volunteer teams
- October 12th and 19th: random team selection
- Everything due 11:59pm October 9th
- In-class evaluation that will be filled out for each project besides your own
   - Need to grade all other groups

**Comment by saltzmanj** [comment]
Presentation is here: [The Keyboard Guys Midterm Design Review](https://docs.google.com/presentation/d/1PqiavUy-WncXATxIO0H5hwtwasshrpzsuzdza-GX9Oc/edit#slide=id.p)

**Comment by arlieu** [comment]
[Image Processing Flow.pptx](https://github.com/saltzmanj/keyboardguys/files/518053/Image.Processing.Flow.pptx)

**Comment by saltzmanj** [comment]
# Parts definitely in the PCB Design

**ICs**
- [TLC5947 24-Channel, 12-Bit PWM LED Driver With Internal Oscillator](http://www.ti.com/lit/ds/symlink/tlc5947.pdf)
- [MAX490 Low-Power, Slew-Rate-Limited RS-485/RS-422 Transceiver](https://datasheets.maximintegrated.com/en/ds/MAX1487-MAX491.pdf)
- [LT1085CT 3A Low Dropout Positive Adjustable Regulator] (https://cds.linear.com/docs/en/datasheet/108345fh.pdf)

**Specialty Devices**
- [22uF Tantalum Caps](https://www.digikey.com/product-detail/en/avx-corporation/TAP226K025SCS/478-1877-ND/563980)

**Wiring**
- [PSR1635 Series 0.100" (2.54mm) Pitch Flat Flex Cable](https://www.digikey.com/catalog/en/partgroup/psr1635-series/1725)

- [14 Positions Header, Shrouded Connector 0.100" (2.54mm) Through Hole, Right Angle Gold](https://www.digikey.com/product-detail/en/sullins-connector-solutions/SBH11-PBPC-D07-RA-BK/S9178-ND/1990071)

- [14 Position Ribbon Cable, DIP Header Connector IDC Through Hole ](https://www.digikey.com/product-detail/en/cnc-tech/3040-14-00/1175-1659-ND/3883759)
   - Can be used in place of the above part. Makes disassembly more difficult, though. Also may be less durable
 
- [14 Conductor Rainbow Ribbon Cable](https://www.digikey.com/product-detail/en/cnc-tech/304-28-14-MC-0250F/CN224MC-10-ND/5864965)

- [4 Position FFC Through-Hole Right angle connector, 2.54mm Pitch](https://www.digikey.com/product-detail/en/te-connectivity-amp-connectors/5-520314-4/A123168-ND/688634)

**Comment by arlieu** [comment]
[Image Processing Flow.pptx](https://github.com/saltzmanj/keyboardguys/files/518092/Image.Processing.Flow.pptx)

I redid most of the flow chart. Hopefully this is detailed enough.

**Comment by saltzmanj** [comment]
Looks good!

**Comment by MrBitSage** [comment]
Old and New Versions of Gantt Chart
Let me know what you think

![keyboardguys_gantt_old](https://cloud.githubusercontent.com/assets/7970325/19222521/89e402be-8e28-11e6-9061-a099819a43c8.png)
![keyboardguys_gantt_mk2](https://cloud.githubusercontent.com/assets/7970325/19222520/89e39da6-8e28-11e6-9f18-ffd3b2dc471d.png)
